/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import processing.core.PApplet;

class AppTest {
    private App testApp;

    // Setting the objects.
    @BeforeEach
    public void setUp(){
        testApp = new App();
    }

    // Tearing down the objects.
    @AfterEach
    public void tearDown(){
        testApp = null;
    }

    // Tests the constructor.
    @Test 
    public void simpleTest() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }
    
}
